export const categories = [
  {
    id: 1,
    name: 'Mỳ cay',
    image: require('../assets/images/mi_cay.jpg'),
  },
  {
    id: 2,
    name: 'Đồ ăn vặt',
    image: require('../assets/images/image_do_an_vat.jpg'),
  },
  {
    id: 3,
    name: 'Sinh tố',
    image: require('../assets/images/image_sinh_to.jpg'),
  },
  {
    id: 4,
    name: 'Đồ đá xay',
    image: require('../assets/images/image_do_da_xay.jpg'),
  },
  {
    id: 5,
    name: 'Sữa chua',
    image: require('../assets/images/iamge_sua_chua.jpg'),
  },
  {
    id: 6,
    name: 'Trà sữa',
    image: require('../assets/images/image_tra_sua.jpg'),
  },
  {
    id: 7,
    name: 'Tàu hũ',
    image: require('../assets/images/image_tau_hu.jpg'),
  },
  {
    id: 8,
    name: 'Đồ uống khác',
    image: require('../assets/images/image_do_uong_khac.jpg'),
  },
  {
    id: 9,
    name: 'Pizza',
    image: require('../assets/images/image_pizza.jpg'),
  },
  {
    id: 10,
    name: 'Lẩu',
    image: require('../assets/images/image_lau.jpg'),
  },
];

export const featured = {
  id: 1,
  title: 'Mỳ cay',
  description: 'Mỳ cay từ 0 -> 7 cấp độ',
  restaurant: [
    {
      id: 1,
      name: 'Mỳ cay bò',
      image: require('../assets/images/my_cay_bo.jpg'),
      description: 'Hot and spicy pizza',
      lng: 38.2145602,
      lat: 38.2145602,
      stars: 4,
      reviews: '4.4k',
      category: 'Fast food',
      dishes: [
        {
          id: 1,
          name: 'pizza',
          description: 'cheezy garlic pizza',
          price: 10,
          image: require('../assets/images/icon_my_home.png'),
        },
        {
          id: 2,
          name: 'pizza',
          description: 'cheezy garlic pizza',
          price: 10,
          image: require('../assets/images/mi_cay.jpg'),
        },
        {
          id: 3,
          name: 'pizza',
          description: 'cheezy garlic pizza',
          price: 10,
          image: require('../assets/images/mi_cay.jpg'),
        },
        {
          id: 4,
          name: 'pizza',
          description: 'cheezy garlic pizza',
          price: 10,
          image: require('../assets/images/mi_cay.jpg'),
        },
        {
          id: 5,
          name: 'pizza',
          description: 'cheezy garlic pizza',
          price: 10,
          image: require('../assets/images/mi_cay.jpg'),
        },
        {
          id: 6,
          name: 'pizza',
          description: 'cheezy garlic pizza',
          price: 10,
          image: require('../assets/images/mi_cay.jpg'),
        },
      ],
    },
    {
      id: 2,
      name: 'Mỳ cay hải sản',
      image: require('../assets/images/mi_cay.jpg'),
      description: 'Hot and spicy pizza',
      lng: 38.2145602,
      lat: 38.2145602,
      stars: 4,
      reviews: '4.4k',
      category: 'Fast food',
      dishes: [
        {
          id: 1,
          name: 'pizza',
          description: 'cheezy garlic pizza',
          price: 10,
          image: require('../assets/images/icon_my_home.png'),
        },
        {
          id: 2,
          name: 'pizza',
          description: 'cheezy garlic pizza',
          price: 10,
          image: require('../assets/images/mi_cay.jpg'),
        },
        {
          id: 3,
          name: 'pizza',
          description: 'cheezy garlic pizza',
          price: 10,
          image: require('../assets/images/mi_cay.jpg'),
        },
        {
          id: 4,
          name: 'pizza',
          description: 'cheezy garlic pizza',
          price: 10,
          image: require('../assets/images/mi_cay.jpg'),
        },
        {
          id: 5,
          name: 'pizza',
          description: 'cheezy garlic pizza',
          price: 10,
          image: require('../assets/images/mi_cay.jpg'),
        },
        {
          id: 6,
          name: 'pizza',
          description: 'cheezy garlic pizza',
          price: 10,
          image: require('../assets/images/mi_cay.jpg'),
        },
      ],
    },
    {
      id: 3,
      name: 'Mỳ cay thập cẩm',
      image: require('../assets/images/my_cay_thap_cam.jpg'),
      description: 'Hot and spicy pizza',
      lng: 38.2145602,
      lat: 38.2145602,
      stars: 4,
      reviews: '4.4k',
      category: 'Fast food',
      dishes: [
        {
          id: 1,
          name: 'pizza',
          description: 'cheezy garlic pizza',
          price: 10,
          image: require('../assets/images/icon_my_home.png'),
        },
        {
          id: 2,
          name: 'pizza',
          description: 'cheezy garlic pizza',
          price: 10,
          image: require('../assets/images/mi_cay.jpg'),
        },
        {
          id: 3,
          name: 'pizza',
          description: 'cheezy garlic pizza',
          price: 10,
          image: require('../assets/images/mi_cay.jpg'),
        },
        {
          id: 4,
          name: 'pizza',
          description: 'cheezy garlic pizza',
          price: 10,
          image: require('../assets/images/mi_cay.jpg'),
        },
        {
          id: 5,
          name: 'pizza',
          description: 'cheezy garlic pizza',
          price: 10,
          image: require('../assets/images/mi_cay.jpg'),
        },
        {
          id: 6,
          name: 'pizza',
          description: 'cheezy garlic pizza',
          price: 10,
          image: require('../assets/images/mi_cay.jpg'),
        },
      ],
    },
  ],
};
export const drinkFeatured = {
  id: 1,
  title: 'Trà sữa',
  description: 'Trà sữa',
  restaurant: [
    {
      id: 1,
      name: 'Hồng trà sữa',
      image: require('../assets/images/image_hong_tra_sua.jpg'),
      description: 'Hot and spicy pizza',
      lng: 38.2145602,
      lat: 38.2145602,
      stars: 4,
      reviews: '4.4k',
      category: 'Fast food',
      dishes: [],
    },
    {
      id: 2,
      name: 'Trà sữa TCDD',
      image: require('../assets/images/image_tra_sua_tcdd.jpg'),
      description: 'Hot and spicy pizza',
      lng: 38.2145602,
      lat: 38.2145602,
      stars: 4,
      reviews: '4.4k',
      category: 'Fast food',
      dishes: [],
    },
    {
      id: 3,
      name: 'Sữa tươi TCDD kem trứng',
      image: require('../assets/images/image_sua_tuoi_tcdd.jpg'),
      description: 'Hot and spicy pizza',
      lng: 38.2145602,
      lat: 38.2145602,
      stars: 4,
      reviews: '4.4k',
      category: 'Fast food',
      dishes: [],
    },
    {
      id: 4,
      name: 'Trà sữa matcha',
      image: require('../assets/images/image_tra_sua_matcha.jpg'),
      description: 'Hot and spicy pizza',
      lng: 38.2145602,
      lat: 38.2145602,
      stars: 4,
      reviews: '4.4k',
      category: 'Fast food',
      dishes: [],
    },
  ],
};
export const hotPodFeatured = {
  id: 1,
  title: 'Lẩu',
  description: 'Lẩu',
  restaurant: [
    {
      id: 1,
      name: 'Lẩu tokbokki',
      image: require('../assets/images/image_lau_tokbokki.jpg'),
      description: 'Hot and spicy pizza',
      lng: 38.2145602,
      lat: 38.2145602,
      stars: 4,
      reviews: '4.4k',
      category: 'Fast food',
      dishes: [],
    },
    {
      id: 2,
      name: 'Lẩu Thái',
      image: require('../assets/images/image_lau_thai.jpg'),
      description: 'Hot and spicy pizza',
      lng: 38.2145602,
      lat: 38.2145602,
      stars: 4,
      reviews: '4.4k',
      category: 'Fast food',
      dishes: [],
    },
    {
      id: 3,
      name: 'Lẩu 2 ngăn',
      image: require('../assets/images/image_lau_2_ngan.jpg'),
      description: 'Hot and spicy pizza',
      lng: 38.2145602,
      lat: 38.2145602,
      stars: 4,
      reviews: '4.4k',
      category: 'Fast food',
      dishes: [],
    },
  ],
};
